apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: falabella-test-api
  labels:
    app: falabella-test

spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: falabella-test
        tier: api
    spec:
      containers:
      - name: falabella-test-api
        image: gcr.io/falabella-test-272122/api:v1
        imagePullPolicy: Always
        ports:
        - name: http-server
          containerPort: 8000
        env:
          - name: falabella-test
            value: falabella-test-272122