apiVersion: v1
kind: Service
metadata:
  name: falabella-test-client
  labels:
    app: falabella-test
    tier: client
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: http-server
  selector:
    app: falabella-test
    tier: client